version: "3"
services:
  # client:
  server:
    build: 
      context: ./server
    ports:
      - "5001:5000"
    environment:
      - PGDATABASE=postgres
      - PGHOST=db
  db:
    build: 
      context: ./db
    volumes:
      - prio-todo:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  prio-todo:

