version: "3"
services:
  client:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - server
    volumes:
      - ./client:/app/
      - /app/node_modules
  server:
    build: 
      context: ./server
    ports:
      - "5001:5000"
    environment:
      - PGDATABASE=postgres
      - PGHOST=db
    depends_on:
      - db
    volumes:
      - ./server:/app/
      - /app/node_modules
  db:
    build: 
      context: ./db
    volumes:
      - prio-todo:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  prio-todo:

