version: 1

services:
  client:
    type: web
    name: client
    env: docker
    buildCommand: npm install # Add any specific commands if needed
    startCommand: npm start
    dockerfilePath: ./client/Dockerfile
    autoDeploy: true
    envVars:
      REACT_APP_API_URL: http://server:5000 # Points to the server service
    healthCheckPath: /

  server:
    type: web
    name: server
    env: docker
    buildCommand: npm install # Adjust based on your server setup
    startCommand: npm start
    dockerfilePath: ./server/Dockerfile
    autoDeploy: true
    envVars:
      PGDATABASE: postgres
      PGHOST: db # Points to the db service
    healthCheckPath: /

  db:
    type: db
    name: database
    env: docker
    dockerfilePath: ./db/Dockerfile # Path to the DB Dockerfile
    volumes:
      - prio-todo:/var/lib/postgresql/data # Ensure volume is correctly configured
