version: 1

services:
  - type: web
    name: client
    env: docker
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: ./client/Dockerfile
    autoDeploy: true
    envVars:
      REACT_APP_API_URL: http://server:5000
    healthCheckPath: /

  - type: web
    name: server
    env: docker
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: ./server/Dockerfile
    autoDeploy: true
    envVars:
      PGDATABASE: postgres
      PGHOST: db
    healthCheckPath: /

  - type: db
    name: database
    env: docker
    dockerfilePath: ./db/Dockerfile
    volumes:
      - prio-todo:/var/lib/postgresql/data

