version: 1

services:
  client:
    type: web
    name: client
    env: docker
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: ./client/Dockerfile
    autoDeploy: true
    envVars:
      REACT_APP_API_URL: http://server:5000
    healthCheckPath: /

  server:
    type: web
    name: server
    env: docker
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: ./server/Dockerfile
    autoDeploy: true
    envVars:
      PGDATABASE: postgres
      PGHOST: db
    healthCheckPath: /

  db:
    type: db
    name: database
    env: docker
    buildCommand: npm install  # Not necessary for databases, adjust as needed
    startCommand: # Your command to start the database (if applicable)
    dockerfilePath: ./db/Dockerfile
    autoDeploy: true
    volumes:
      - prio-todo:/var/lib/postgresql/data